version: '2'
services:
  yii2-broadcast-redis:
      container_name: yii2-broadcast-redis
      image: redis:3.0.7
      restart: always
      networks:
        - yii2-broadcast-net
  yii2-broadcast-laravel-echo:
      container_name: yii2-broadcast-laravel-echo
      build: ./laravel-echo
      restart: always
      ports:
        - "6001:6001"
      links:
        - yii2-broadcast-redis
      depends_on:
        - yii2-broadcast-redis
      networks:
        - yii2-broadcast-net
networks:
  yii2-broadcast-net:
    ipam:
      driver: default
      config:
        - subnet: 173.1.0.0/16